### ISSUE TITLE
Compilation issues on macOS Sierra 10.12.6

### ISSUE THREAD

**Issue by avivbeeri** [x43x61x69/gbdk-osx#2]
I had some errors while running `make`. Initially it complained about sdcc/bin not being created and then it complained about "SDCC.y:1004:12: error: label at end of compound statement: expected statement default:"

I removed the duplicate break statement here and it all built successfully. Not sure if it might break something though.

https://github.com/x43x61x69/gbdk-osx/blob/b72af061630a5c3c38f921b55262ba7e7ffcd375/sdcc/src/SDCC.y#L1005

**Comment by x43x61x69** [comment]
You can send a pull request so I can merge it to `master`.

Thanks.
